export const dataPostImage = [
	{
		postType: 'tweet',
		description: 'AJAJAJAJAAJA',
		likesCount: 1,
		username: 'hola',
		image: '.www',
		isLiked: true,
		isSaved: false,
	},
	{
		postType: 'tweet',
		description: 'AJAJAJAJAAJA',
		likesCount: 1,
		username: 'hola',
		image: '.www',
		isLiked: true,
		isSaved: false,
	},
	{
		postType: 'tweet',
		description: 'AJAJAJAJAAJA',
		likesCount: 1,
		username: 'hola',
		image: '.www',
		isLiked: true,
		isSaved: false,
	},
	{
		postType: 'tweet',
		description: 'AJAJAJAJAAJA',
		likesCount: 1,
		username: 'hola',
		image: '.www',
		isLiked: true,
		isSaved: false,
	},
	{
		postType: 'post',
		description: 'AJAJAJAJAAJA',
		likesCount: 1,
		username: 'hola',
		image: '.www',
		isLiked: true,
		isSaved: false,
	},
	{
		postType: 'post',
		description: 'AJAJAJAJAAJA',
		likesCount: 1,
		username: 'hola',
		image: '.www',
		isLiked: true,
		isSaved: false,
	},
];
